services:
  music-bot:
    build: .
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      COMMAND_PREFIX_LETTER: ${COMMAND_PREFIX_LETTER:-t}
      MAX_PLAYLIST_ITEMS: ${MAX_PLAYLIST_ITEMS:-100}
